# Generated by Django 5.0.4 on 2024-04-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_details', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=400)),
                ('vendor_code', models.AutoField(primary_key=True, serialize=False)),
                ('on_time_delivery_rate', models.FloatField(blank=True)),
                ('quality_rating_avg', models.FloatField(blank=True)),
                ('average_response_time', models.FloatField(blank=True)),
                ('fulfillment_rate', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on_time_delivery_rate', models.FloatField(default=None)),
                ('quality_rating_avg', models.FloatField(default=None)),
                ('average_response_time', models.FloatField(default=None)),
                ('fulfillment_rate', models.FloatField(default=None)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_cms.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('po_number', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('cancelled', 'CANCELLED'), ('delivered', 'DELIVERED')], max_length=10)),
                ('quality_rating', models.FloatField()),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_cms.vendor')),
            ],
        ),
    ]
