# Generated by Django 5.0.4 on 2024-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
